name: Deploy to Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app to Fly.io
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Verify deployment
        run: |
          echo "🚀 Deployment completed successfully!"
          echo "App is available at: https://practicefusion-agent.com/"
          
      - name: Health check
        run: |
          # Wait for deployment to stabilize
          sleep 30
          
          # Test the custom domain
          response=$(curl -s -o /dev/null -w "%{http_code}" https://practicefusion-agent.com/.well-known/agent-card.json || echo "000")
          
          if [ "$response" = "200" ]; then
            echo "✅ Health check passed - Custom domain is responding"
            echo "🌐 Agent card available at: https://practicefusion-agent.com/.well-known/agent-card.json"
          else
            echo "⚠️  Health check: Got HTTP $response - Domain may still be propagating"
            echo "📊 Monitor at: https://fly.io/apps/lang-a2a-cardio/monitoring"
          fi