name: Deploy to Fly.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy app to Fly.io
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Verify deployment
        run: |
          echo "🚀 Deployment completed successfully!"
          echo "App is available at: https://lang-a2a-cardio.fly.dev/"
          
      - name: Health check
        run: |
          # Wait a bit for deployment to stabilize
          sleep 30
          
          # Check if the app is responding
          response=$(curl -s -o /dev/null -w "%{http_code}" https://lang-a2a-cardio.fly.dev/.well-known/agent-card.json || echo "000")
          
          if [ "$response" = "200" ]; then
            echo "✅ Health check passed - Agent card endpoint is responding"
          else
            echo "❌ Health check failed - Got HTTP $response"
            exit 1
          fi